/*
 * Created 2017-2-17 16:13:14
 */
package cn.com.yting.kxy.battle.executor;

import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import cn.com.yting.kxy.core.parameter.ParameterNameConstants;

/**
 *
 * @author Azige
 */
public class ParameterEditorDialog extends javax.swing.JDialog{

    /**
     * Creates new form ParamterEditorDialog
     */
    public ParameterEditorDialog(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        parameterTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("参数编辑");
        setModal(true);

        parameterTable.setModel(createTableModel());
        jScrollPane1.setViewportView(parameterTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private TableModel createTableModel(){
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("参数名");
        tableModel.addColumn("参数值");
        Stream.of(ParameterNameConstants.class.getFields())
            .forEach(field -> {
                try{
                    String parameterName = (String)field.get(null);
                    tableModel.addRow(new String[]{parameterName, "0"});
                }catch (IllegalArgumentException | IllegalAccessException ex){
                    ex.printStackTrace();
                }
            });
        return tableModel;
    }

    public Map<String,Double> doEdit(Map<String,Double> parameterMap){
        TableModel tableModel = parameterTable.getModel();
        for (int i = 0; i < tableModel.getRowCount(); i++){
            String parameterName = (String)tableModel.getValueAt(i, 0);
            if (parameterMap.containsKey(parameterName)){
                tableModel.setValueAt(String.valueOf(parameterMap.get(parameterName)), i, 1);
            }
        }
        setVisible(true);
        Map<String,Double> newParameterMap = new HashMap<>();
        for (int i = 0; i < tableModel.getRowCount(); i++){
            newParameterMap.put((String)tableModel.getValueAt(i, 0), Double.parseDouble((String)tableModel.getValueAt(i, 1)));
        }
        return newParameterMap;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable parameterTable;
    // End of variables declaration//GEN-END:variables
}
