/*
 * Created 2017-2-17 17:58:16
 */
package cn.com.yting.kxy.battle.executor;

import cn.com.yting.kxy.battle.skill.resource.SkillParam;
import cn.com.yting.kxy.core.resource.ResourceContext;
import cn.com.yting.kxy.core.resource.ResourceContextHolder;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Azige
 */
public class SkillEditorDialog extends javax.swing.JDialog {

    private List<Long> skillIds;
    private List<SkillParam> skillParams = new ArrayList<>();
    private DefaultListModel<String> listModel;

    /**
     * Creates new form SkillEditorDialog
     */
    public SkillEditorDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        skillList = new javax.swing.JList<>();
        addByIdButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("技能编辑");
        setModal(true);

        jScrollPane1.setViewportView(skillList);

        addByIdButton.setText("按id添加");
        addByIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addByIdButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("删除");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addByIdButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addByIdButton)
                    .addComponent(deleteButton))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addByIdButtonActionPerformed
        String input = JOptionPane.showInputDialog(this, "输入技能id");
        if (input != null) {
            try {
                long id = Long.parseLong(input);
                ResourceContext context = ResourceContextHolder.getResourceContext();
                SkillParam skillParam = context.getLoader(SkillParam.class).get(id);
                if (skillParam == null) {
                    JOptionPane.showMessageDialog(this, "技能不存在，id=" + id);
                } else {
                    skillParams.add(skillParam);
                    listModel.addElement(skillParam.getName());
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "技能id格式有误");
            }
        }
    }//GEN-LAST:event_addByIdButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selectedIndex = skillList.getSelectedIndex();
        if (selectedIndex == -1) {
            return;
        }
        listModel.remove(selectedIndex);
        skillParams.remove(selectedIndex);
    }//GEN-LAST:event_deleteButtonActionPerformed

    public List<SkillParam> doEdit(List<SkillParam> originalSkills) {
        listModel = new DefaultListModel<>();
        originalSkills.forEach(sp -> listModel.addElement(sp.getName()));
        skillList.setModel(listModel);
        skillParams = new ArrayList<>(originalSkills);
        setVisible(true);
        return skillParams;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addByIdButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> skillList;
    // End of variables declaration//GEN-END:variables
}
